// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk600834046/appengine/go_appengine/goroot-1.6`
const TheVersion = `1.6.4 (appengine-1.9.62)`
const Goexperiment = ``
const StackGuardMultiplier = 1

