// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk331654961/appengine/go_appengine/goroot-1.8`
const TheVersion = `1.8.5 (appengine-1.9.68)`
const Goexperiment = ``
const StackGuardMultiplier = 1

