// auto generated by go tool dist

package sys

const DefaultGoroot = `/private/var/folders/43/mwptjdv50qlg0yfkw2fpspr40000gn/T/appengine/go_appengine/goroot`
const TheVersion = `go1.6.3 (appengine-1.9.46)`
const Goexperiment = ``
const StackGuardMultiplier = 1

