// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/go_sdk331654961/appengine/go_appengine/goroot-1.9`
const TheVersion = `1.9.2 (appengine-1.9.68)`
const Goexperiment = ``
const StackGuardMultiplier = 1

